"""Game constants for Color Tiles."""

# 보드 설정
BOARD_WIDTH = 23
BOARD_HEIGHT = 15
TOTAL_CELLS = BOARD_WIDTH * BOARD_HEIGHT  # 345

# 타일 설정
NUM_COLORS = 10
TILES_PER_COLOR = 20
TOTAL_TILES = NUM_COLORS * TILES_PER_COLOR  # 200
EMPTY_CELLS = TOTAL_CELLS - TOTAL_TILES  # 145

# 시간 및 점수
INITIAL_TIME = 120.0  # seconds
PENALTY_TIME = 10.0  # seconds
POINTS_PER_TILE = 1

# 이동 요구사항
MIN_TILES_FOR_REMOVAL = 2
